show databases;
create database Product;
use Product;
show databases;
show tables;
create table Product_info(id integer, Productname varchar(50), Qunatity integer, price integer);
insert into Product_info(id,Productname,Qunatity,price) value (1, 'Mobile', 10, 300000);
select * from Product_info;
insert into Product_info(id,Productname,Qunatity,price) value (2, 'Laptop', 5, 900000);
insert into Product_info(id,Productname,Qunatity,price) value (3, 'TV', 20, 400000);
insert into Product_info(id,Productname,Qunatity,price) value (4, 'Mouse', 100, 500);
insert into Product_info(id,Productname,Qunatity,price) value (5, 'Keyboard', 90, 1000);
